gnosis: 5
mage_arcana: 4
highest_arcanum: 3
yantras: 2
places_of_power: 1
supporting_crafters: 1
is_persistent: yes
is_duration_extra_reach: yes
duration_penalty: -4
primary_factor: a
extra_reaches: 2
mana_battery: 2
prior_craftings: 3
is_praxis: yes
is_perfected: no
potency: 5
spell_range: b
is_sympathetic: yes
is_temporal_sympathy: no